#!/bin/sh
# remove default OpenWrt or LEDE wifi interfaces if present
ssid1=$(uci get wireless.@wifi-iface[1].ssid 2> /dev/null)
if [ "$ssid1" == "OpenWrt" ] || [ "$ssid1" == "lede" ]; then
    uci delete wireless.@wifi-iface[1]
fi
ssid0=$(uci get wireless.@wifi-iface[0].ssid 2> /dev/null)
if [ "$ssid0" == "OpenWrt" ] || [ "$ssid0" == "lede" ]; then
    uci delete wireless.@wifi-iface[0]
fi
uci commit wireless
exit 0
